# Generated by Django 4.2.21 on 2025-05-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0005_alter_project_team_alter_task_project_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="team",
        ),
        migrations.AddField(
            model_name="project",
            name="teams",
            field=models.ManyToManyField(
                related_name="projects", to="task_manager.team"
            ),
        ),
    ]
